name: Run k6 Tests

on:
  pull_request:
    branches:
      - master

jobs:
  k6_test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install -g k6

      - name: Run k6 Tests
        run: k6 run src/test/k6/k6-test/script.getvets.js

  merge_check:
    runs-on: ubuntu-latest

    needs: k6_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge Check
        run: echo "Merge Check Successful"
